import NavProvider from "@/context/NavProvider";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";

const gems = localFont({
  src: "../fonts/Gemsbuck01Black-axn2g.ttf",
  variable: "--font-gems",
  display: "swap",
});

const uncut = localFont({
  src: "../fonts/Uncut-Sans-VF.ttf",
  variable: "--font-uncut",
  display: "swap",
});

const humane = localFont({
  src: "../fonts/Humane-Bold.ttf",
  variable: "--font-humane",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${uncut.variable} ${gems.variable} ${humane.variable} font-uncut`}
      >
        <NavProvider>{children}</NavProvider>
      </body>
    </html>
  );
}
